---
kind: Namespace
apiVersion: v1
metadata:
  name: nginx-gateway
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nginx-gateway-fabric
  namespace: nginx-gateway
spec:
  type: oci
  interval: 1h0s
  url: oci://ghcr.io/nginx/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-gateway-fabric
  namespace: nginx-gateway
spec:
  interval: 15m
  chart:
    spec:
      chart: nginx-gateway-fabric
      sourceRef:
        kind: HelmRepository
        name: nginx-gateway-fabric
  values:
    nginx:
      service:
        patches:
        - type: StrategicMerge
          value:
            metadata:
              annotations:
                metallb.io/loadBalancerIPs: '192.168.1.16'
