---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: external-snapshotter
  namespace: flux-system
spec:
  interval: 1h
  ref:
    semver: '*'
  url: https://github.com/kubernetes-csi/external-snapshotter.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-snapshotter-crds
  namespace: flux-system
spec:
  interval: 15m
  path: ./client/config/crd
  prune: true
  sourceRef:
    kind: GitRepository
    name: external-snapshotter
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-snapshotter-controller
  namespace: flux-system
spec:
  interval: 10m
  path: ./deploy/kubernetes/snapshot-controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: external-snapshotter
  dependsOn:
    - name: external-snapshotter-crds