{
   "apiVersion": "kustomize.config.k8s.io/v1beta1",
   "configMapGenerator": [
      {
         "files": [
            "kubernetes-devcontainer/README.md",
            "kubernetes-devcontainer/main.tf"
         ],
         "name": "coder",
         "namespace": "coder"
      }
   ],
   "configurations": [
      "namereference.yaml"
   ],
   "generatorOptions": {
      "annotations": {
         "kustomize.toolkit.fluxcd.io/substitute": "disabled"
      }
   },
   "kind": "Kustomization",
   "resources": [
      "helmrelease.yaml",
      "helmrepository.yaml",
      "httproute.yaml",
      "namespace.yaml",
      "onepassword_coder.yaml",
      "pvc_coder-db.yaml",
      "role_coder-init.yaml",
      "rolebinding_coder-init.yaml",
      "service_coder-db.yaml",
      "serviceaccount.yaml",
      "statefulset.yaml"
   ]
}
