{
   "apiVersion": "external-secrets.io/v1",
   "kind": "ExternalSecret",
   "metadata": {
      "name": "fancl20",
      "namespace": "coder"
   },
   "spec": {
      "dataFrom": [
         {
            "extract": {
               "key": "Coder Workspace"
            }
         }
      ],
      "refreshInterval": "1m",
      "secretStoreRef": {
         "kind": "ClusterSecretStore",
         "name": "onepassword"
      },
      "target": {
         "creationPolicy": "Owner",
         "name": "fancl20"
      }
   }
}
