{
   "apiVersion": "rbac.authorization.k8s.io/v1",
   "kind": "Role",
   "metadata": {
      "name": "coder",
      "namespace": "coder"
   },
   "rules": [
      {
         "apiGroups": [
            ""
         ],
         "resources": [
            "secrets"
         ],
         "verbs": [
            "create",
            "update"
         ]
      }
   ]
}
