{
   "apiVersion": "rbac.authorization.k8s.io/v1",
   "kind": "RoleBinding",
   "metadata": {
      "name": "coder",
      "namespace": "coder"
   },
   "roleRef": {
      "apiGroup": "rbac.authorization.k8s.io",
      "kind": "Role",
      "name": "coder"
   },
   "subjects": [
      {
         "kind": "ServiceAccount",
         "name": "coder",
         "namespace": "coder"
      }
   ]
}
