{
   "apiVersion": "apps/v1",
   "kind": "Deployment",
   "metadata": {
      "annotations": {
         "kustomize.toolkit.fluxcd.io/substitute": "disabled"
      },
      "name": "n8n",
      "namespace": "default"
   },
   "spec": {
      "replicas": 1,
      "selector": {
         "matchLabels": {
            "app.kubernetes.io/name": "n8n"
         }
      },
      "strategy": {
         "rollingUpdate": {
            "maxSurge": 0,
            "maxUnavailable": "100%"
         }
      },
      "template": {
         "metadata": {
            "annotations": { },
            "labels": {
               "app.kubernetes.io/name": "n8n"
            }
         },
         "spec": {
            "containers": [
               {
                  "env": [
                     {
                        "name": "N8N_PROTOCOL",
                        "value": "http"
                     },
                     {
                        "name": "N8N_PORT",
                        "value": "5678"
                     },
                     {
                        "name": "N8N_EDITOR_BASE_URL",
                        "value": "https://n8n.local.d20.fan/"
                     },
                     {
                        "name": "VUE_APP_URL_BASE_API",
                        "value": "https://n8n.local.d20.fan/"
                     }
                  ],
                  "image": "docker.io/n8nio/n8n",
                  "name": "n8n",
                  "volumeMounts": [
                     {
                        "mountPath": "/home/node/.n8n",
                        "name": "n8n"
                     }
                  ]
               }
            ],
            "enableServiceLinks": false,
            "securityContext": {
               "fsGroup": 1000,
               "fsGroupChangePolicy": "OnRootMismatch",
               "runAsGroup": 1000,
               "runAsUser": 1000
            },
            "serviceAccountName": "n8n",
            "volumes": [
               {
                  "name": "n8n",
                  "persistentVolumeClaim": {
                     "claimName": "n8n"
                  }
               }
            ]
         }
      }
   }
}
