{
   "apiVersion": "v1",
   "kind": "Service",
   "metadata": {
      "annotations": { },
      "name": "n8n",
      "namespace": "default"
   },
   "spec": {
      "ports": [
         {
            "name": "webui",
            "port": 5678,
            "protocol": "TCP",
            "targetPort": 5678
         }
      ],
      "selector": {
         "app.kubernetes.io/name": "n8n"
      },
      "type": "ClusterIP"
   }
}
