apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-multus-ds
  namespace: kube-system
spec:
  template:
    spec:
      initContainers:
      - name: pull-cni-plugings
        image: quay.io/skopeo/stable:v1.21.0 # {"$imagepolicy": "flux-system:multus-cni-skopeo"}
        command: ['/bin/sh', '-c', 'skopeo copy "docker://${CNI_PLUGINS_IMAGE}" dir:/workspace']
        env:
        - name: CNI_PLUGINS_IMAGE
          value: ghcr.io/siderolabs/cni:v1.11.0 # {"$imagepolicy": "flux-system:multus-cni-plugins"}
        volumeMounts:
        - name: cniplugins
          mountPath: /workspace
      - name: install-cni-plugings
        image: docker.io/library/python:3.14.3-slim # {"$imagepolicy": "flux-system:multus-cni-python"}
        command:
        - '/usr/local/bin/python3'
        - '-c'
        - |
          import json
          import tarfile
          with open('manifest.json') as f:
            for l in json.load(f)['layers']:
              t = tarfile.open(l['digest'].split(':')[1])
              t.extractall('/host', filter='data')
        workingDir: /workspace
        volumeMounts:
        - name: cnibin
          mountPath: /host/opt/cni/bin
        - name: cniplugins
          mountPath: /workspace
      volumes:
      - name: cniplugins
        emptyDir: {}
