{
   "apiVersion": "image.toolkit.fluxcd.io/v1beta2",
   "kind": "ImagePolicy",
   "metadata": {
      "name": "buildkit",
      "namespace": "flux-system"
   },
   "spec": {
      "filterTags": {
         "pattern": "^v[0-9.]*-rootless$"
      },
      "imageRepositoryRef": {
         "name": "buildkit"
      },
      "policy": {
         "semver": {
            "range": "*-rootless"
         }
      }
   }
}
