{
   "apiVersion": "image.toolkit.fluxcd.io/v1beta2",
   "kind": "ImageRepository",
   "metadata": {
      "name": "kea",
      "namespace": "flux-system"
   },
   "spec": {
      "image": "docker.cloudsmith.io/isc/docker/kea-dhcp4",
      "interval": "1h"
   }
}
