{
   "apiVersion": "image.toolkit.fluxcd.io/v1beta2",
   "kind": "ImagePolicy",
   "metadata": {
      "name": "paperless-ngx",
      "namespace": "flux-system"
   },
   "spec": {
      "filterTags": {
         "pattern": ".*"
      },
      "imageRepositoryRef": {
         "name": "paperless-ngx"
      },
      "policy": {
         "semver": {
            "range": "*"
         }
      }
   }
}
