{
   "apiVersion": "image.toolkit.fluxcd.io/v1beta2",
   "kind": "ImagePolicy",
   "metadata": {
      "name": "postgres",
      "namespace": "flux-system"
   },
   "spec": {
      "imageRepositoryRef": {
         "name": "postgres"
      },
      "policy": {
         "numerical": {
            "order": "asc"
         }
      }
   }
}
