{
   "apiVersion": "image.toolkit.fluxcd.io/v1beta2",
   "kind": "ImagePolicy",
   "metadata": {
      "name": "roon",
      "namespace": "flux-system"
   },
   "spec": {
      "filterTags": {
         "pattern": "^[0-9]+\\.[0-9]+$"
      },
      "imageRepositoryRef": {
         "name": "roon"
      },
      "policy": {
         "alphabetical": {
            "order": "asc"
         }
      }
   }
}
