apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: lscr.io/linuxserver/beets # {"$imagepolicy": "flux-system:beets:name"}
  newTag: '2.5.1-ls299' # {"$imagepolicy": "flux-system:beets:tag"}
- name: internetsystemsconsortium/bind9 # {"$imagepolicy": "flux-system:bind9:name"}
  newTag: '9.21' # {"$imagepolicy": "flux-system:bind9:tag"}
- name: lscr.io/linuxserver/calibre-web # {"$imagepolicy": "flux-system:calibreb:name"}
  newTag: '0.6.25-ls359' # {"$imagepolicy": "flux-system:calibre:tag"}
- name: registry.local.d20.fan/fancl20/dae # {"$imagepolicy": "flux-system:dae:name"}
  newTag: '1.0.0-testing-20251117' # {"$imagepolicy": "flux-system:dae:tag"}
- name: registry.k8s.io/external-dns/external-dns # {"$imagepolicy": "flux-system:external-dns:name"}
  newTag: 'v0.20.0' # {"$imagepolicy": "flux-system:external-dns:tag"}
- name: registry.local.d20.fan/fancl20/fava # {"$imagepolicy": "flux-system:fava:name"}
  newTag: '1.30.7-testing-20251117' # {"$imagepolicy": "flux-system:fava:tag"}
- name: lscr.io/linuxserver/jellyfin # {"$imagepolicy": "flux-system:jellyfin:name"}
  newTag: '10.8.13-1-ls247' # {"$imagepolicy": "flux-system:jellyfin:tag"}
- name: docker.io/library/mongo # {"$imagepolicy": "flux-system:mongo:name"}
  newTag: '8.2.2' # {"$imagepolicy": "flux-system:mongo:tag"}
- name: docker.io/library/nginx # {"$imagepolicy": "flux-system:nginx:name"}
  newTag: '1.29.3' # {"$imagepolicy": "flux-system:nginx:tag"}
- name: lscr.io/linuxserver/openssh-server # {"$imagepolicy": "flux-system:openssh:name"}
  newTag: '10.0_p1-r9-ls210' # {"$imagepolicy": "flux-system:openssh:tag"}
- name: docker.io/library/mongo # {"$imagepolicy": "flux-system:mongo:name"}
  newTag: '8.2.2' # {"$imagepolicy": "flux-system:mongo:tag"}
- name: lscr.io/linuxserver/qbittorrent # {"$imagepolicy": "flux-system:qbittorrent:name"}
  newTag: '5.1.4-r0-ls429' # {"$imagepolicy": "flux-system:qbittorrent:tag"}
- name: docker.io/library/registry # {"$imagepolicy": "flux-system:registry:name"}
  newTag: '3.0.0' # {"$imagepolicy": "flux-system:registry:tag"}
- name: registry.local.d20.fan/fancl20/roon # {"$imagepolicy": "flux-system:roon:name"}
  newTag: '205601582-testing-20251117' # {"$imagepolicy": "flux-system:roon:tag"}
- name: lscr.io/linuxserver/unifi-network-application # {"$imagepolicy": "flux-system:unifi:name"}
  newTag: '10.0.160-ls110' # {"$imagepolicy": "flux-system:unifi:tag"}
