apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: lscr.io/linuxserver/beets # {"$imagepolicy": "flux-system:beets:name"}
  newTag: '2.6.1-ls311' # {"$imagepolicy": "flux-system:beets:tag"}
- name: internetsystemsconsortium/bind9 # {"$imagepolicy": "flux-system:bind9:name"}
  newTag: '9.21' # {"$imagepolicy": "flux-system:bind9:tag"}
- name: lscr.io/linuxserver/calibre-web # {"$imagepolicy": "flux-system:calibre:name"}
  newTag: '0.6.26-ls370' # {"$imagepolicy": "flux-system:calibre:tag"}
- name: registry.local.d20.fan/fancl20/dae # {"$imagepolicy": "flux-system:dae:name"}
  newTag: '1.0.0-testing-20260202' # {"$imagepolicy": "flux-system:dae:tag"}
- name: docker.io/library/debian # {"$imagepolicy": "flux-system:debian:name"}
  newTag: 'testing-20260202' # {"$imagepolicy": "flux-system:debian:tag"}
- name: registry.k8s.io/external-dns/external-dns # {"$imagepolicy": "flux-system:external-dns:name"}
  newTag: 'v0.20.0' # {"$imagepolicy": "flux-system:external-dns:tag"}
- name: registry.local.d20.fan/fancl20/fava # {"$imagepolicy": "flux-system:fava:name"}
  newTag: '1.30.11-testing-20260202' # {"$imagepolicy": "flux-system:fava:tag"}
- name: lscr.io/linuxserver/jellyfin # {"$imagepolicy": "flux-system:jellyfin:name"}
  newTag: '10.8.13-1-ls247' # {"$imagepolicy": "flux-system:jellyfin:tag"}
- name: docker.io/library/mongo # {"$imagepolicy": "flux-system:mongo:name"}
  newTag: '8.2.5' # {"$imagepolicy": "flux-system:mongo:tag"}
- name: docker.io/library/nginx # {"$imagepolicy": "flux-system:nginx:name"}
  newTag: '1.29.5' # {"$imagepolicy": "flux-system:nginx:tag"}
- name: lscr.io/linuxserver/openssh-server # {"$imagepolicy": "flux-system:openssh:name"}
  newTag: '10.2_p1-r0-ls216' # {"$imagepolicy": "flux-system:openssh:tag"}
- name: ghcr.io/paperless-ngx/paperless-ngx # {"$imagepolicy": "flux-system:paperless-ngx:name"}
  newTag: '2.20.6' # {"$imagepolicy": "flux-system:paperless-ngx:tag"}
- name: docker.io/library/postgres # {"$imagepolicy": "flux-system:postgres:name"}
  newTag: '18.2' # {"$imagepolicy": "flux-system:postgres:tag"}
- name: lscr.io/linuxserver/qbittorrent # {"$imagepolicy": "flux-system:qbittorrent:name"}
  newTag: '5.1.4-r2-ls441' # {"$imagepolicy": "flux-system:qbittorrent:tag"}
- name: docker.io/library/redis # {"$imagepolicy": "flux-system:redis:name"}
  newTag: '8.6.0' # {"$imagepolicy": "flux-system:redis:tag"}
- name: docker.io/library/registry # {"$imagepolicy": "flux-system:registry:name"}
  newTag: '3.0.0' # {"$imagepolicy": "flux-system:registry:tag"}
- name: registry.local.d20.fan/fancl20/roon # {"$imagepolicy": "flux-system:roon:name"}
  newTag: '206001629-testing-20260202' # {"$imagepolicy": "flux-system:roon:tag"}
- name: lscr.io/linuxserver/unifi-network-application # {"$imagepolicy": "flux-system:unifi:name"}
  newTag: '10.1.85-ls117' # {"$imagepolicy": "flux-system:unifi:tag"}
- name: docker.io/velero/velero-plugin-for-aws # {"$imagepolicy": "flux-system:velero-plugin-aws:name"}
  newTag: 'v1.13.2' # {"$imagepolicy": "flux-system:velero-plugin-aws:tag"}
- name: docker.io/jetbrains/youtrack # {"$imagepolicy": "flux-system:youtrack:name"}
  newTag: '2025.3.121962' # {"$imagepolicy": "flux-system:youtrack:tag"}
- name: docker.io/n8nio/n8n # {"$imagepolicy": "flux-system:n8n:name"}
  newTag: '2.8.3' # {"$imagepolicy": "flux-system:n8n:tag"}
