{
   "apiVersion": "apps/v1",
   "kind": "Deployment",
   "metadata": {
      "annotations": {
         "kustomize.toolkit.fluxcd.io/substitute": "disabled"
      },
      "name": "roon-server",
      "namespace": "default"
   },
   "spec": {
      "replicas": 1,
      "selector": {
         "matchLabels": {
            "app.kubernetes.io/name": "roon-server"
         }
      },
      "strategy": {
         "rollingUpdate": {
            "maxSurge": 0,
            "maxUnavailable": "100%"
         }
      },
      "template": {
         "metadata": {
            "annotations": {
               "k8s.v1.cni.cncf.io/networks": "[\n    {\n        \"ips\": [\n            \"192.168.1.31/24\"\n        ],\n        \"name\": \"macvlan-static\"\n    }\n]"
            },
            "labels": {
               "app.kubernetes.io/name": "roon-server"
            }
         },
         "spec": {
            "containers": [
               {
                  "command": [
                     "/bin/bash",
                     "-ex",
                     "-c",
                     "ip route replace 10.96.0.0/12 via 10.244.0.1 dev eth0 onlink # serviceCIDR\nip route replace default via 192.168.1.1 dev net1\n\nexec /opt/roon/RoonServer/start.sh\n"
                  ],
                  "env": [
                     {
                        "name": "TZ",
                        "value": "Australia/Sydney"
                     }
                  ],
                  "image": "registry.local.d20.fan/fancl20/roon",
                  "name": "roon-server",
                  "securityContext": {
                     "capabilities": {
                        "add": [
                           "NET_ADMIN"
                        ]
                     }
                  },
                  "volumeMounts": [
                     {
                        "mountPath": "/data",
                        "name": "roon-server",
                        "subPath": "data"
                     },
                     {
                        "mountPath": "/backup",
                        "name": "roon-server",
                        "subPath": "backup"
                     },
                     {
                        "mountPath": "/music",
                        "name": "data",
                        "subPath": "music"
                     }
                  ]
               }
            ],
            "enableServiceLinks": false,
            "serviceAccountName": "roon-server",
            "volumes": [
               {
                  "name": "data",
                  "persistentVolumeClaim": {
                     "claimName": "shared-data"
                  }
               },
               {
                  "name": "roon-server",
                  "persistentVolumeClaim": {
                     "claimName": "roon-server"
                  }
               }
            ]
         }
      }
   }
}
