{
   "apiVersion": "gateway.networking.k8s.io/v1",
   "kind": "HTTPRoute",
   "metadata": {
      "name": "fava",
      "namespace": "default"
   },
   "spec": {
      "hostnames": [
         "*.fava.local.d20.fan"
      ],
      "parentRefs": [
         {
            "group": "gateway.networking.k8s.io",
            "kind": "Gateway",
            "name": "default",
            "namespace": "nginx-gateway",
            "sectionName": "https"
         }
      ],
      "rules": [
         {
            "backendRefs": [
               {
                  "group": "",
                  "kind": "Service",
                  "name": "fava",
                  "port": 80
               }
            ]
         }
      ]
   }
}
