apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: wildcard-tls-gateway
  namespace: nginx-gateway
spec:
  listeners:
  - name: local
    protocol: HTTPS
    port: 443
    hostname: '*.local.d20.fan'
    tls:
      certificateRefs:
      - group: ""
        kind: Secret
        name: d20-fan-tls
        namespace: cert-manager
