{
   "apiVersion": "apps/v1",
   "kind": "Deployment",
   "metadata": {
      "annotations": {
         "kustomize.toolkit.fluxcd.io/substitute": "disabled"
      },
      "name": "dae",
      "namespace": "default"
   },
   "spec": {
      "replicas": 1,
      "selector": {
         "matchLabels": {
            "app.kubernetes.io/name": "dae"
         }
      },
      "strategy": {
         "rollingUpdate": {
            "maxSurge": 0,
            "maxUnavailable": "100%"
         }
      },
      "template": {
         "metadata": {
            "annotations": {
               "k8s.v1.cni.cncf.io/networks": "[\n    {\n        \"ips\": [\n            \"192.168.1.245/24\"\n        ],\n        \"name\": \"macvlan-static\"\n    }\n]"
            },
            "labels": {
               "app.kubernetes.io/name": "dae"
            }
         },
         "spec": {
            "containers": [
               {
                  "command": [
                     "/bin/bash",
                     "-ex",
                     "-c",
                     "mount bpffs /sys/fs/bpf/ -t bpf\n\nsysctl -w net.ipv4.conf.net1.forwarding=1\nsysctl -w net.ipv6.conf.net1.forwarding=1\nsysctl -w net.ipv4.conf.net1.send_redirects=0\n\nip route replace 10.96.0.0/12 via 10.244.0.1 dev eth0 onlink # serviceCIDR\nip route replace default via 192.168.1.1 dev net1\n\nexec /opt/dae/dae-linux-x86_64_v3_avx2 run --disable-timestamp -c /etc/dae/config.dae\n"
                  ],
                  "env": [
                     {
                        "name": "TZ",
                        "value": "Australia/Sydney"
                     }
                  ],
                  "image": "registry.local.d20.fan/fancl20/dae",
                  "name": "dae",
                  "securityContext": {
                     "capabilities": {
                        "add": [
                           "NET_ADMIN",
                           "BPF",
                           "SYS_ADMIN"
                        ]
                     },
                     "privileged": true
                  },
                  "volumeMounts": [
                     {
                        "mountPath": "/etc/dae",
                        "name": "config"
                     }
                  ]
               }
            ],
            "dnsConfig": {
               "nameservers": [
                  "8.8.8.8",
                  "8.8.4.4"
               ]
            },
            "dnsPolicy": "None",
            "enableServiceLinks": false,
            "serviceAccountName": "dae",
            "volumes": [
               {
                  "name": "config",
                  "projected": {
                     "defaultMode": 384,
                     "sources": [
                        {
                           "configMap": {
                              "name": "dae"
                           }
                        },
                        {
                           "secret": {
                              "name": "dae"
                           }
                        }
                     ]
                  }
               }
            ]
         }
      }
   }
}
