{
   "apiVersion": "v1",
   "kind": "PersistentVolumeClaim",
   "metadata": {
      "name": "kea",
      "namespace": "default"
   },
   "spec": {
      "accessModes": [
         "ReadWriteMany"
      ],
      "resources": {
         "requests": {
            "storage": "8Gi"
         }
      },
      "volumeMode": "Filesystem"
   }
}
