{
   "apiVersion": "source.toolkit.fluxcd.io/v1",
   "kind": "HelmRepository",
   "metadata": {
      "name": "velero",
      "namespace": "velero"
   },
   "spec": {
      "interval": "1h0s",
      "url": "https://vmware-tanzu.github.io/helm-charts"
   }
}
