{
   "apiVersion": "apps/v1",
   "kind": "StatefulSet",
   "metadata": {
      "annotations": {
         "kustomize.toolkit.fluxcd.io/substitute": "disabled"
      },
      "name": "coder-db",
      "namespace": "coder"
   },
   "spec": {
      "replicas": 1,
      "selector": {
         "matchLabels": {
            "app.kubernetes.io/name": "coder-db"
         }
      },
      "serviceName": "coder-db",
      "strategy": {
         "rollingUpdate": {
            "maxSurge": 0,
            "maxUnavailable": "100%"
         }
      },
      "template": {
         "metadata": {
            "annotations": { },
            "labels": {
               "app.kubernetes.io/name": "coder-db"
            }
         },
         "spec": {
            "containers": [
               {
                  "envFrom": [
                     {
                        "secretRef": {
                           "name": "coder-db"
                        }
                     }
                  ],
                  "image": "docker.io/library/postgres",
                  "name": "postgres",
                  "volumeMounts": [
                     {
                        "mountPath": "/var/lib/postgresql",
                        "name": "coder-db"
                     }
                  ]
               }
            ],
            "serviceAccountName": "coder-db",
            "volumes": [
               {
                  "name": "coder-db",
                  "persistentVolumeClaim": {
                     "claimName": "coder-db"
                  }
               }
            ]
         }
      }
   }
}
