machine:
  nodeLabels:
    node.kubernetes.io/instance-type: rpi-cm4
  sysctls:
    user.max_user_namespaces: '11255'
  install:
    disk: '/dev/mmcblk0'
    image: 'factory.talos.dev/installer/${TALOS_SCHEMATIC}:${TALOS_VERSION}'
    wipe: true
cluster:
  controlPlane:
    endpoint: 'https://192.168.1.3:6443'
