---
apiVersion: v1alpha1
kind: BondConfig
name: bond0
links: [ enp5s0, enp6s0 ]
bondMode: 802.3ad
miimon: 100
updelay: 200
downdelay: 200
xmitHashPolicy: layer3+4
lacpRate: slow
adActorSysPrio: 65535
resendIGMP: 1
packetsPerSlave: 1
addresses: [{ address: '${NODE_ADDRESS}/24' }]
routes: [{ gateway: '192.168.1.1' }]
