{
   "apiVersion": "apps/v1",
   "kind": "Deployment",
   "metadata": {
      "annotations": {
         "kustomize.toolkit.fluxcd.io/substitute": "disabled"
      },
      "name": "beets",
      "namespace": "default"
   },
   "spec": {
      "replicas": 1,
      "selector": {
         "matchLabels": {
            "app.kubernetes.io/name": "beets"
         }
      },
      "strategy": {
         "rollingUpdate": {
            "maxSurge": 0,
            "maxUnavailable": "100%"
         }
      },
      "template": {
         "metadata": {
            "annotations": { },
            "labels": {
               "app.kubernetes.io/name": "beets"
            }
         },
         "spec": {
            "containers": [
               {
                  "env": [
                     {
                        "name": "TZ",
                        "value": "Australia/Sydney"
                     },
                     {
                        "name": "PUID",
                        "value": "1000"
                     },
                     {
                        "name": "PGID",
                        "value": "1000"
                     }
                  ],
                  "image": "lscr.io/linuxserver/beets",
                  "name": "beets",
                  "volumeMounts": [
                     {
                        "mountPath": "/config",
                        "name": "beets"
                     },
                     {
                        "mountPath": "/music",
                        "name": "data",
                        "subPath": "music"
                     },
                     {
                        "mountPath": "/downloads",
                        "name": "data",
                        "subPath": "downloads"
                     }
                  ]
               }
            ],
            "serviceAccountName": "beets",
            "volumes": [
               {
                  "name": "data",
                  "persistentVolumeClaim": {
                     "claimName": "shared-data"
                  }
               },
               {
                  "name": "beets",
                  "persistentVolumeClaim": {
                     "claimName": "beets"
                  }
               }
            ]
         }
      }
   }
}
