---
kind: Namespace
apiVersion: v1
metadata:
  name: argo
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argo-server
  namespace: argo
spec:
  hostnames:
  - argo.local.d20.fan
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: default
    namespace: nginx-gateway
    sectionName: https
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: argo-server
      port: 2746