---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.160-192.168.1.191
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: reserved
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.1-192.168.1.31
  autoAssign: false

