{
   "apiVersion": "apps/v1",
   "kind": "Deployment",
   "metadata": {
      "annotations": {
         "kustomize.toolkit.fluxcd.io/substitute": "disabled"
      },
      "name": "paperless",
      "namespace": "default"
   },
   "spec": {
      "replicas": 1,
      "selector": {
         "matchLabels": {
            "app.kubernetes.io/name": "paperless"
         }
      },
      "strategy": {
         "rollingUpdate": {
            "maxSurge": 0,
            "maxUnavailable": "100%"
         }
      },
      "template": {
         "metadata": {
            "annotations": { },
            "labels": {
               "app.kubernetes.io/name": "paperless"
            }
         },
         "spec": {
            "containers": [
               {
                  "env": [
                     {
                        "name": "PAPERLESS_REDIS",
                        "value": "redis://127.0.0.1:6379"
                     },
                     {
                        "name": "PAPERLESS_URL",
                        "value": "https://paperless.local.d20.fan"
                     },
                     {
                        "name": "PAPERLESS_TIME_ZONE",
                        "value": "Australia/Sydney"
                     },
                     {
                        "name": "USERMAP_UID",
                        "value": "1000"
                     },
                     {
                        "name": "USERMAP_GID",
                        "value": "1000"
                     }
                  ],
                  "image": "ghcr.io/paperless-ngx/paperless-ngx",
                  "name": "paperless",
                  "volumeMounts": [
                     {
                        "mountPath": "/usr/src/paperless/data",
                        "name": "paperless",
                        "subPath": "paperless/data"
                     },
                     {
                        "mountPath": "/usr/src/paperless/media",
                        "name": "paperless",
                        "subPath": "paperless/media"
                     },
                     {
                        "mountPath": "/usr/src/paperless/export",
                        "name": "paperless",
                        "subPath": "paperless/export"
                     },
                     {
                        "mountPath": "/usr/src/paperless/consume",
                        "name": "paperless",
                        "subPath": "paperless/consume"
                     }
                  ]
               },
               {
                  "image": "docker.io/library/redis",
                  "name": "redis",
                  "volumeMounts": [
                     {
                        "mountPath": "/data",
                        "name": "paperless",
                        "subPath": "redis/data"
                     }
                  ]
               }
            ],
            "enableServiceLinks": false,
            "serviceAccountName": "paperless",
            "volumes": [
               {
                  "name": "paperless",
                  "persistentVolumeClaim": {
                     "claimName": "paperless"
                  }
               }
            ]
         }
      }
   }
}
