{
   "apiVersion": "v1",
   "kind": "Service",
   "metadata": {
      "annotations": { },
      "name": "paperless",
      "namespace": "default"
   },
   "spec": {
      "ports": [
         {
            "name": "webui",
            "port": 80,
            "protocol": "TCP",
            "targetPort": 8000
         }
      ],
      "selector": {
         "app.kubernetes.io/name": "paperless"
      },
      "type": "ClusterIP"
   }
}
