---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 05-stage
  namespace: flux-system
spec:
  dependsOn:
  - name: 04-stage
  interval: 15m
  path: ./configs/clusters/production/05-stage
  prune: true
  sourceRef:
    kind: GitRepository
    name: configs
  healthChecks:
  # Rook-Ceph
  - apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    name: rook-ceph-cluster
    namespace: rook-ceph
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    name: rook-cephfs
