---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gateway-crds
  namespace: flux-system
spec:
  interval: 1h
  ref:
    semver: '*'
  url: https://github.com/kubernetes-sigs/gateway-api.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-crds
  namespace: flux-system
spec:
  interval: 15m
  path: ./config/crd/standard
  prune: true
  sourceRef:
    kind: GitRepository
    name: gateway-crds